### ISSUE TITLE
MVPA geeft error

### ISSUE THREAD

**Issue by JJStekelenburg** [JakeLmp/SpeechAdaptation#1]
Hoi Jakob,
Als ik MVPA run dan lijkt het net of hij bepaalde modules niet kan vinden.
Ik heb geen idee waarom niet.

gr. Jeroen

PS C:\Onderzoek\Decoding\Speech_Adaptation adaptors\MVPA> python -m MVPA
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Onderzoek\Decoding\Speech_Adaptation adaptors\MVPA\MVPA.py", line 18, in <module>
    import MVPA.utils, MVPA.stat_utils
  File "C:\Onderzoek\Decoding\Speech_Adaptation adaptors\MVPA\MVPA.py", line 18, in <module>
    import MVPA.utils, MVPA.stat_utils
ModuleNotFoundError: No module named 'MVPA.utils'; 'MVPA' is not a package

**Comment by JakeLmp** [comment]
Hi Jeroen,


Wat vervelend!
Dit klinkt als een reference error in mijn code.

Ik zit alleen de komende twee maanden in Zuid-Afrika, zonder laptop of
makkelijke toegang tot een pc...
Misschien kan Harm Brouwer helpen? (of hij weet iemand die kan helpen)

Het enige wat ik nu kan aanraden is een volledige reset, dus alles opnieuw
downloaden in een vers mapje, en dan nog eens proberen.

Sorry voor het ongemak ;) en succes!


Groeten,

Jakob

**Comment by JJStekelenburg** [comment]
Hoi Jakob,

Heerlijk, twee maanden in de bushbush!
Geniet er maar van...(jouw vriendin aan het werk en jij lekker vakantie:
goed geregeld!)

Ik zal het eens opnieuw downloaden.
Anders vraag ik je het over twee maanden nog eens, als je terug bent.

Groetjes,
Jeroen


Op wo 3 apr 2024 om 17:39 schreef JakeLmp ***@***.***>:

> Hi Jeroen,
>
>
> Wat vervelend!
> Dit klinkt als een reference error in mijn code.
>
> Ik zit alleen de komende twee maanden in Zuid-Afrika, zonder laptop of
> makkelijke toegang tot een pc...
> Misschien kan Harm Brouwer helpen? (of hij weet iemand die kan helpen)
>
> Het enige wat ik nu kan aanraden is een volledige reset, dus alles opnieuw
> downloaden in een vers mapje, en dan nog eens proberen.
>
> Sorry voor het ongemak ;) en succes!
>
>
> Groeten,
>
> Jakob
>
>
